version: "3"
services:
  web:
    # Pull the image we uploaded in step 2 from the registry.
    image: andrewfowler/get-started:part2
    # Run 5 instances of that image as a service called web, 
    # limiting each one to use, at most, 10% of the CPU (across all cores), and 50MB of RAM.
    deploy:
      replicas: 8
      resources:
        limits:
          cpus: "0.1"
          memory: 50M
      # Immediately restart containers if one fails.
      restart_policy:
        condition: on-failure
    # Map port 80 on the host to web’s port 80.
    ports:
      - "80:80"
    # Instruct web’s containers to share port 80 via a load-balanced network called webnet. 
    # (Internally, the containers themselves will publish to web’s port 80 at an ephemeral port.)
    networks:
      - webnet
# Define the webnet network with the default settings (which is a load-balanced overlay network).      
networks:
  webnet: